### ISSUE TITLE
AIResponse context parsing problem

### ISSUE THREAD

**Issue by i-Alex** [api-ai/api-ai-net#5]
In a case when developer creates composite entity, we get the next structure of answer's context :
"contexts": [
      {
        "name": "spec_statistics_out_context",
        "parameters": {
          "option.original": "best devices",
          "option": {
            "count_stat": {
              "what": "TopDevices",
              "what.original": "devices"
            },
            "count_stat.original": "best devices"
          }
        },
        "lifespan": 1
      }
    ],
The problem is in "parameters field". In SDK in Context class field 'parameter'  has type  Dictionary<string, string>. But as you can see in example, we can retrieve pair <string, object> as well.
here we get an error from Newtonsoft.JSON lib and can't get response on user request.

Edit1: the error only occured, when Intent with such composit entity also has other contexts (out\in)

**Comment by xVir** [comment]
Hi, @i-Alex 
Sorry for the late answer.

I've fixed the problem in https://github.com/api-ai/api-ai-net/commit/4640515737ce109cea26f8184dadc958dffd4a73 and released new version of the SDK.

Please try to update the library and check it.

Thanks.
