### ISSUE TITLE
actionIncomplete field not returned in Response

### ISSUE THREAD

**Issue by pmiri** [api-ai/api-ai-net#7]
Response.result does not contain the actionIncomplete field. It would be necessary for those who want to ensure a complete conversation before executing specific code.

**Comment by xVir** [comment]
Hi, @pmiri 
Thanks for the note! 
We will add the filed soon.

Thanks.

**Comment by xVir** [comment]
Hi, @pmiri 
Thanks for your pull request!

I've just published release 1.6.5 with your change.

Thanks!

**Comment by pmiri** [comment]
Thanks a lot! I will go ahead and test changes, but this should close the issue.

**Comment by GauravGGTrilyo** [comment]
How to use this version???
