### ISSUE TITLE
QuestionMetadata.SessionId is marked as Internal

### ISSUE THREAD

**Issue by Zhaph** [api-ai/api-ai-net#9]
According to the [/query documentation](https://docs.api.ai/docs/query), `sessionId` is required and enables us to link messages together into a single session - is there a reason why the SessionId property is marked as internal?

Shouldn't a consumer be able to set this to some conversation specific id to link queries and contexts together?

**Comment by xVir** [comment]
Hi @Zhaph 
You could set `SessionId` using [AIConfiguration](https://github.com/api-ai/api-ai-net/blob/master/ApiAiSDK/AIConfiguration.cs#L41). In `AIDataService` it made as read-only to prevent unintentional changing of the field.

Thanks!

**Comment by Zhaph** [comment]
Thanks for that, I'll give it a try and let you know.

Cheers,

Ben

**Comment by Zhaph** [comment]
@xVir Thanks, that does indeed appear to work as I need.

**Comment by xVir** [comment]
Thanks, @Zhaph!
